---
- name: Install MongoDB package
  apt:
    name:
    - gnupg
    state: present

- name: Add MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add MongoDB APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB package
  apt:
    name: mongodb-org
    state: present

- name: Ensure mongod user exists
  user:
    name:
    - mongod
    - mongodb-mongosh
    state: present
    system: yes

- name: Create environment files
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongod
    group: mongod
    mode: '0644'
  notify: Restart MongoDB

- name: Create MongoDB database using cmd module
  command:
    cmd: mongosh --eval "use documentation" --quiet

- name: Create MongoDB database using cmd module
  command:
    cmd: mongosh --eval 'show dbs' --quiet


- name: Start and enable MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes