all:
  children:
    front:
      hosts:
        front-user:
          ansible_host: 192.168.1.52
          ansible_user: root
          ansible_ssh_pass: password
        front-admin:
          ansible_host: 192.168.1.50
          ansible_user: root
          ansible_ssh_pass: password
    api:
      hosts:
        api-user:
          ansible_host: 192.168.1.51
          ansible_user: root
          ansible_ssh_pass: password
        api-admin:
          ansible_host: 192.168.1.49
          ansible_user: root
          ansible_ssh_pass: password
    database:
      hosts:
        mongodb:
          ansible_host: 192.168.1.53
          ansible_user: root
          ansible_ssh_pass: passwor
